project:
  type: website
  output-dir: docs

website:
  title: "Quarto Explorations"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: lyra.qmd
        text: Lyra
      - href: recipes.qmd
        text: Recipes
      - href: lterdatasampler.qmd
        text: LTER Data Sampler

format:
  html:
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

editor: visual



